# Generated by Django 5.0.7 on 2024-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
